services:
  bng-techspike-calculation:
    build:
      context: .
      target: production
    image: bng-techspike-calculation
    container_name: bng-techspike-calculation
    environment:
      APPINSIGHTS_CLOUDROLE: bng-techspike-calculation-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
