# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  bng-techspike-calculation:
    build:
      target: development
    image: bng-techspike-calculation-development
    container_name: bng-techspike-calculation-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
