apiVersion: v2
description: Techspike for BNG calculation
name: bng-techspike-calculation
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 3.4.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
